spring.application.name=collab

# mysql database connection
spring.datasource.url=jdbc:mysql://localhost:3306/my_collab
spring.datasource.username=root
spring.datasource.password=Karan@144007#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true